/** Generated by scripts/split-adhan-chunks.mjs. Do not edit by hand. */
export const ADHAN_CHUNK_LISTS = {
  "alafasy": {
    "duration": 257.166,
    "chunks": [
      {
        "file": "adhan_alafasy_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_alafasy_01.caf",
        "offset": 20.668
      },
      {
        "file": "adhan_alafasy_02.caf",
        "offset": 40.123
      },
      {
        "file": "adhan_alafasy_03.caf",
        "offset": 63.498
      },
      {
        "file": "adhan_alafasy_04.caf",
        "offset": 81.069
      },
      {
        "file": "adhan_alafasy_05.caf",
        "offset": 102.446
      },
      {
        "file": "adhan_alafasy_06.caf",
        "offset": 123.024
      },
      {
        "file": "adhan_alafasy_07.caf",
        "offset": 141.647
      },
      {
        "file": "adhan_alafasy_08.caf",
        "offset": 161.966
      },
      {
        "file": "adhan_alafasy_09.caf",
        "offset": 181.554
      },
      {
        "file": "adhan_alafasy_10.caf",
        "offset": 197.67
      },
      {
        "file": "adhan_alafasy_11.caf",
        "offset": 215.699
      },
      {
        "file": "adhan_alafasy_12.caf",
        "offset": 235.091
      },
      {
        "file": "adhan_alafasy_13.caf",
        "offset": 247.966
      }
    ]
  },
  "alafasy_fajr": {
    "duration": 288.494,
    "chunks": [
      {
        "file": "adhan_alafasy_fajr_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_alafasy_fajr_01.caf",
        "offset": 20.532
      },
      {
        "file": "adhan_alafasy_fajr_02.caf",
        "offset": 40.075
      },
      {
        "file": "adhan_alafasy_fajr_03.caf",
        "offset": 63.535
      },
      {
        "file": "adhan_alafasy_fajr_04.caf",
        "offset": 81.176
      },
      {
        "file": "adhan_alafasy_fajr_05.caf",
        "offset": 102.643
      },
      {
        "file": "adhan_alafasy_fajr_06.caf",
        "offset": 123.307
      },
      {
        "file": "adhan_alafasy_fajr_07.caf",
        "offset": 142.006
      },
      {
        "file": "adhan_alafasy_fajr_08.caf",
        "offset": 162.408
      },
      {
        "file": "adhan_alafasy_fajr_09.caf",
        "offset": 182.073
      },
      {
        "file": "adhan_alafasy_fajr_10.caf",
        "offset": 198.212
      },
      {
        "file": "adhan_alafasy_fajr_11.caf",
        "offset": 214.488
      },
      {
        "file": "adhan_alafasy_fajr_12.caf",
        "offset": 232.719
      },
      {
        "file": "adhan_alafasy_fajr_13.caf",
        "offset": 246.928
      },
      {
        "file": "adhan_alafasy_fajr_14.caf",
        "offset": 266.391
      },
      {
        "file": "adhan_alafasy_fajr_15.caf",
        "offset": 279.266
      }
    ]
  },
  "abdulbasit": {
    "duration": 188.949,
    "chunks": [
      {
        "file": "adhan_abdulbasit_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_abdulbasit_01.caf",
        "offset": 29.363
      },
      {
        "file": "adhan_abdulbasit_02.caf",
        "offset": 57.464
      },
      {
        "file": "adhan_abdulbasit_03.caf",
        "offset": 69.845
      },
      {
        "file": "adhan_abdulbasit_04.caf",
        "offset": 92.15
      },
      {
        "file": "adhan_abdulbasit_05.caf",
        "offset": 105.746
      },
      {
        "file": "adhan_abdulbasit_06.caf",
        "offset": 132.125
      },
      {
        "file": "adhan_abdulbasit_07.caf",
        "offset": 162.166
      },
      {
        "file": "adhan_abdulbasit_08.caf",
        "offset": 177.407
      }
    ]
  },
  "abdulbasit_fajr": {
    "duration": 293.454,
    "chunks": [
      {
        "file": "adhan_abdulbasit_fajr_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_abdulbasit_fajr_01.caf",
        "offset": 27.5
      },
      {
        "file": "adhan_abdulbasit_fajr_02.caf",
        "offset": 55
      },
      {
        "file": "adhan_abdulbasit_fajr_03.caf",
        "offset": 82.5
      },
      {
        "file": "adhan_abdulbasit_fajr_04.caf",
        "offset": 110
      },
      {
        "file": "adhan_abdulbasit_fajr_05.caf",
        "offset": 137.5
      },
      {
        "file": "adhan_abdulbasit_fajr_06.caf",
        "offset": 165
      },
      {
        "file": "adhan_abdulbasit_fajr_07.caf",
        "offset": 192.5
      },
      {
        "file": "adhan_abdulbasit_fajr_08.caf",
        "offset": 220
      },
      {
        "file": "adhan_abdulbasit_fajr_09.caf",
        "offset": 247.5
      },
      {
        "file": "adhan_abdulbasit_fajr_10.caf",
        "offset": 275
      }
    ]
  },
  "trablsy": {
    "duration": 242.917,
    "chunks": [
      {
        "file": "adhan_trablsy_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_trablsy_01.caf",
        "offset": 16.253
      },
      {
        "file": "adhan_trablsy_02.caf",
        "offset": 32.808
      },
      {
        "file": "adhan_trablsy_03.caf",
        "offset": 48.77
      },
      {
        "file": "adhan_trablsy_04.caf",
        "offset": 67.443
      },
      {
        "file": "adhan_trablsy_05.caf",
        "offset": 85.387
      },
      {
        "file": "adhan_trablsy_06.caf",
        "offset": 108.002
      },
      {
        "file": "adhan_trablsy_07.caf",
        "offset": 128.543
      },
      {
        "file": "adhan_trablsy_08.caf",
        "offset": 158.685
      },
      {
        "file": "adhan_trablsy_09.caf",
        "offset": 178.932
      },
      {
        "file": "adhan_trablsy_10.caf",
        "offset": 209.713
      },
      {
        "file": "adhan_trablsy_11.caf",
        "offset": 224.115
      }
    ]
  },
  "trablsy_fajr": {
    "duration": 229.464,
    "chunks": [
      {
        "file": "adhan_trablsy_fajr_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_trablsy_fajr_01.caf",
        "offset": 13.797
      },
      {
        "file": "adhan_trablsy_fajr_02.caf",
        "offset": 30.713
      },
      {
        "file": "adhan_trablsy_fajr_03.caf",
        "offset": 47.229
      },
      {
        "file": "adhan_trablsy_fajr_04.caf",
        "offset": 59.815
      },
      {
        "file": "adhan_trablsy_fajr_05.caf",
        "offset": 77.253
      },
      {
        "file": "adhan_trablsy_fajr_06.caf",
        "offset": 95.785
      },
      {
        "file": "adhan_trablsy_fajr_07.caf",
        "offset": 116.846
      },
      {
        "file": "adhan_trablsy_fajr_08.caf",
        "offset": 135.88
      },
      {
        "file": "adhan_trablsy_fajr_09.caf",
        "offset": 154.784
      },
      {
        "file": "adhan_trablsy_fajr_10.caf",
        "offset": 173.23
      },
      {
        "file": "adhan_trablsy_fajr_11.caf",
        "offset": 187.5
      },
      {
        "file": "adhan_trablsy_fajr_12.caf",
        "offset": 200.993
      },
      {
        "file": "adhan_trablsy_fajr_13.caf",
        "offset": 213.404
      }
    ]
  },
  "mulla": {
    "duration": 246.412,
    "chunks": [
      {
        "file": "adhan_mulla_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_mulla_01.caf",
        "offset": 15.998
      },
      {
        "file": "adhan_mulla_02.caf",
        "offset": 43.498
      },
      {
        "file": "adhan_mulla_03.caf",
        "offset": 67.622
      },
      {
        "file": "adhan_mulla_04.caf",
        "offset": 96.293
      },
      {
        "file": "adhan_mulla_05.caf",
        "offset": 112.832
      },
      {
        "file": "adhan_mulla_06.caf",
        "offset": 130.229
      },
      {
        "file": "adhan_mulla_07.caf",
        "offset": 150.981
      },
      {
        "file": "adhan_mulla_08.caf",
        "offset": 171.208
      },
      {
        "file": "adhan_mulla_09.caf",
        "offset": 194.084
      },
      {
        "file": "adhan_mulla_10.caf",
        "offset": 215.585
      },
      {
        "file": "adhan_mulla_11.caf",
        "offset": 231.223
      }
    ]
  },
  "mulla_fajr": {
    "duration": 222.976,
    "chunks": [
      {
        "file": "adhan_mulla_fajr_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_mulla_fajr_01.caf",
        "offset": 16.578
      },
      {
        "file": "adhan_mulla_fajr_02.caf",
        "offset": 33.604
      },
      {
        "file": "adhan_mulla_fajr_03.caf",
        "offset": 48.657
      },
      {
        "file": "adhan_mulla_fajr_04.caf",
        "offset": 66.269
      },
      {
        "file": "adhan_mulla_fajr_05.caf",
        "offset": 82.761
      },
      {
        "file": "adhan_mulla_fajr_06.caf",
        "offset": 99.508
      },
      {
        "file": "adhan_mulla_fajr_07.caf",
        "offset": 117.531
      },
      {
        "file": "adhan_mulla_fajr_08.caf",
        "offset": 134.003
      },
      {
        "file": "adhan_mulla_fajr_09.caf",
        "offset": 150.908
      },
      {
        "file": "adhan_mulla_fajr_10.caf",
        "offset": 167.481
      },
      {
        "file": "adhan_mulla_fajr_11.caf",
        "offset": 181.072
      },
      {
        "file": "adhan_mulla_fajr_12.caf",
        "offset": 196.083
      },
      {
        "file": "adhan_mulla_fajr_13.caf",
        "offset": 208.534
      }
    ]
  },
  "bokhari": {
    "duration": 281.836,
    "chunks": [
      {
        "file": "adhan_bokhari_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_bokhari_01.caf",
        "offset": 18.152
      },
      {
        "file": "adhan_bokhari_02.caf",
        "offset": 38.658
      },
      {
        "file": "adhan_bokhari_03.caf",
        "offset": 56.665
      },
      {
        "file": "adhan_bokhari_04.caf",
        "offset": 84.165
      },
      {
        "file": "adhan_bokhari_05.caf",
        "offset": 108.354
      },
      {
        "file": "adhan_bokhari_06.caf",
        "offset": 130.771
      },
      {
        "file": "adhan_bokhari_07.caf",
        "offset": 149.287
      },
      {
        "file": "adhan_bokhari_08.caf",
        "offset": 170.055
      },
      {
        "file": "adhan_bokhari_09.caf",
        "offset": 197.555
      },
      {
        "file": "adhan_bokhari_10.caf",
        "offset": 225.055
      },
      {
        "file": "adhan_bokhari_11.caf",
        "offset": 252.555
      }
    ]
  },
  "bokhari_fajr": {
    "duration": 278.848,
    "chunks": [
      {
        "file": "adhan_bokhari_fajr_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_bokhari_fajr_01.caf",
        "offset": 27.5
      },
      {
        "file": "adhan_bokhari_fajr_02.caf",
        "offset": 55
      },
      {
        "file": "adhan_bokhari_fajr_03.caf",
        "offset": 82.5
      },
      {
        "file": "adhan_bokhari_fajr_04.caf",
        "offset": 110
      },
      {
        "file": "adhan_bokhari_fajr_05.caf",
        "offset": 137.5
      },
      {
        "file": "adhan_bokhari_fajr_06.caf",
        "offset": 165
      },
      {
        "file": "adhan_bokhari_fajr_07.caf",
        "offset": 192.5
      },
      {
        "file": "adhan_bokhari_fajr_08.caf",
        "offset": 220
      },
      {
        "file": "adhan_bokhari_fajr_09.caf",
        "offset": 247.5
      },
      {
        "file": "adhan_bokhari_fajr_10.caf",
        "offset": 275
      }
    ]
  },
  "ozcan": {
    "duration": 178.372,
    "chunks": [
      {
        "file": "adhan_ozcan_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_ozcan_01.caf",
        "offset": 23.502
      },
      {
        "file": "adhan_ozcan_02.caf",
        "offset": 39.628
      },
      {
        "file": "adhan_ozcan_03.caf",
        "offset": 51.164
      },
      {
        "file": "adhan_ozcan_04.caf",
        "offset": 67.52
      },
      {
        "file": "adhan_ozcan_05.caf",
        "offset": 80.181
      },
      {
        "file": "adhan_ozcan_06.caf",
        "offset": 107.681
      },
      {
        "file": "adhan_ozcan_07.caf",
        "offset": 119.664
      },
      {
        "file": "adhan_ozcan_08.caf",
        "offset": 147.164
      },
      {
        "file": "adhan_ozcan_09.caf",
        "offset": 164.425
      }
    ]
  },
  "ozcan_fajr": {
    "duration": 178.372,
    "chunks": [
      {
        "file": "adhan_ozcan_fajr_00.caf",
        "offset": 0
      },
      {
        "file": "adhan_ozcan_fajr_01.caf",
        "offset": 23.502
      },
      {
        "file": "adhan_ozcan_fajr_02.caf",
        "offset": 39.628
      },
      {
        "file": "adhan_ozcan_fajr_03.caf",
        "offset": 51.164
      },
      {
        "file": "adhan_ozcan_fajr_04.caf",
        "offset": 67.52
      },
      {
        "file": "adhan_ozcan_fajr_05.caf",
        "offset": 80.181
      },
      {
        "file": "adhan_ozcan_fajr_06.caf",
        "offset": 107.681
      },
      {
        "file": "adhan_ozcan_fajr_07.caf",
        "offset": 119.664
      },
      {
        "file": "adhan_ozcan_fajr_08.caf",
        "offset": 147.164
      },
      {
        "file": "adhan_ozcan_fajr_09.caf",
        "offset": 164.425
      }
    ]
  }
} as const
