export type RestaurantCity = "Makkah" | "Madinah"

export type Restaurant = {
  id: string
  name: string
  distance: string
  cuisine: string
  priceRange: "$" | "$$" | "$$$"
  rating: number
  isOpen: boolean
  type: "ours" | "external"
  city: RestaurantCity
  image: string
  description: string
  features: string[]
  lat: number
  lng: number
  website: string
  address: string
  halal: true
  /** Shown first / hero treatment */
  featured?: boolean
  chain?: string
}

/**
 * Pilgrim-focused restaurants near Masjid al-Haram & Masjid al-Nabawi.
 * Al Baik is the iconic featured hero.
 */
export const RESTAURANTS: Restaurant[] = [
  // ═══════════════════════════════════════════
  // FEATURED · Al Baik (hero)
  // ═══════════════════════════════════════════
  {
    id: "albaik-makkah",
    name: "Al Baik",
    distance: "300m from Haram · Jabal Omar",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.9,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800",
    description:
      "Saudi Arabia’s most iconic broasted chicken chain — a must for pilgrims. Multiple Makkah branches including Jabal Omar / Souk Al Khalil near Masjid al-Haram.",
    features: ["Halal certified", "Broasted chicken", "Family meals", "Takeaway", "Late hours"],
    lat: 21.4198,
    lng: 39.8232,
    website: "https://www.albaik.com",
    address: "Souk Al Khalil / Jabal Omar area, near Masjid al-Haram, Makkah",
    halal: true,
    featured: true,
    chain: "Al Baik",
  },
  {
    id: "albaik-madinah",
    name: "Al Baik",
    distance: "5 min walk from Nabawi",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.8,
    isOpen: true,
    type: "ours",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=800",
    description:
      "The famous Al Baik branch near Masjid al-Nabawi on King Faisal Road — pilgrims’ favourite quick meal after prayers.",
    features: ["Halal certified", "Closest Nabawi branch", "Broasted chicken", "Takeaway"],
    lat: 24.4688,
    lng: 39.6102,
    website: "https://www.albaik.com",
    address: "King Faisal Road, Bani Khidrah, Madinah 42311",
    halal: true,
    featured: true,
    chain: "Al Baik",
  },

  // ═══════════════════════════════════════════
  // EXISTING LOCAL FAVOURITES (kept)
  // ═══════════════════════════════════════════
  {
    id: "r2",
    name: "Zamzam Restaurant",
    distance: "150m from Haram",
    cuisine: "🍖 Arabic",
    priceRange: "$$",
    rating: 4.7,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    description: "Traditional Arabic dishes with a clean and welcoming atmosphere near the Haram.",
    features: ["Halal certified", "Arabic platters", "Prayer break friendly", "Family sections"],
    lat: 21.4215,
    lng: 39.8255,
    website: "https://www.google.com/maps/search/?api=1&query=Zamzam+Restaurant+Makkah",
    address: "Near Masjid al-Haram, Makkah",
    halal: true,
  },
  {
    id: "r3",
    name: "Layali Al Sham",
    distance: "500m from Nabawi",
    cuisine: "🌍 Syrian",
    priceRange: "$$",
    rating: 4.6,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
    description: "Authentic Levantine meals with grilled specialties near Masjid al-Nabawi.",
    features: ["Halal certified", "Grills", "Mixed platters", "Desserts"],
    lat: 24.4695,
    lng: 39.6135,
    website: "https://www.google.com/maps/search/?api=1&query=Layali+Al+Sham+Madinah",
    address: "Central Area, Madinah",
    halal: true,
  },
  {
    id: "r4",
    name: "Makkah Grill House",
    distance: "100m from Haram",
    cuisine: "🍖 Grills",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    description: "Charcoal-grilled meats and fresh sides very close to Haram.",
    features: ["Halal certified", "BBQ", "Fresh salads", "Quick service"],
    lat: 21.4220,
    lng: 39.8258,
    website: "https://www.google.com/maps/search/?api=1&query=Makkah+Grill+House",
    address: "Ajyad area, Makkah",
    halal: true,
  },
  {
    id: "r5",
    name: "Al Nakheel",
    distance: "200m from Haram",
    cuisine: "🍖 Arabic",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800",
    description: "Simple Arabic comfort food at affordable prices.",
    features: ["Halal certified", "Budget friendly", "Casual dining"],
    lat: 21.4210,
    lng: 39.8265,
    website: "https://www.google.com/maps/search/?api=1&query=Al+Nakheel+Restaurant+Makkah",
    address: "Near Haram, Makkah",
    halal: true,
  },
  {
    id: "r6",
    name: "Haram View Cafe",
    distance: "80m from Haram",
    cuisine: "☕ Cafe",
    priceRange: "$",
    rating: 4.6,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
    description: "Light meals and coffee with a convenient Haram-side location.",
    features: ["Halal certified", "Coffee", "Snacks", "Desserts"],
    lat: 21.4222,
    lng: 39.8260,
    website: "https://www.google.com/maps/search/?api=1&query=Cafe+near+Masjid+al+Haram+Makkah",
    address: "Haram perimeter, Makkah",
    halal: true,
  },
  {
    id: "r7",
    name: "Najd Village",
    distance: "600m from Haram",
    cuisine: "🍖 Arabic",
    priceRange: "$$$",
    rating: 4.7,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800",
    description: "Heritage-style dining with classic Saudi recipes.",
    features: ["Halal certified", "Traditional menu", "Group seating"],
    lat: 21.4185,
    lng: 39.8280,
    website: "https://www.google.com/maps/search/?api=1&query=Najd+Village+Makkah",
    address: "Makkah",
    halal: true,
  },
  {
    id: "r9",
    name: "Kabab & Grills",
    distance: "400m from Nabawi",
    cuisine: "🍖 Kabab",
    priceRange: "$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800",
    description: "Affordable kabab meals with local flavors near Nabawi.",
    features: ["Halal certified", "Takeaway", "Late hours"],
    lat: 24.4680,
    lng: 39.6125,
    website: "https://www.google.com/maps/search/?api=1&query=Kabab+Grills+Madinah",
    address: "Central Area, Madinah",
    halal: true,
  },
  {
    id: "r10",
    name: "Istanbul Restaurant",
    distance: "500m from Haram",
    cuisine: "🌍 Turkish",
    priceRange: "$$",
    rating: 4.6,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800",
    description: "Turkish specialties and grilled meats in a relaxed setting.",
    features: ["Halal certified", "Turkish menu", "Family seating"],
    lat: 21.4200,
    lng: 39.8270,
    website: "https://www.google.com/maps/search/?api=1&query=Istanbul+Restaurant+Makkah",
    address: "Ajyad / Haram area, Makkah",
    halal: true,
  },
  {
    id: "r11",
    name: "Karachi Darbar",
    distance: "700m from Haram",
    cuisine: "🌍 Pakistani",
    priceRange: "$",
    rating: 4.5,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800",
    description: "Spiced curries and rice dishes with generous servings.",
    features: ["Halal certified", "Biryani", "Curry dishes"],
    lat: 21.4175,
    lng: 39.8285,
    website: "https://www.google.com/maps/search/?api=1&query=Karachi+Darbar+Makkah",
    address: "Near Haram, Makkah",
    halal: true,
  },
  {
    id: "r12",
    name: "Indian Palace",
    distance: "600m from Nabawi",
    cuisine: "🌍 Indian",
    priceRange: "$$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800",
    description: "Classic Indian dishes near central Madinah.",
    features: ["Halal certified", "Vegetarian options", "Tandoori"],
    lat: 24.4665,
    lng: 39.6140,
    website: "https://www.google.com/maps/search/?api=1&query=Indian+Palace+Madinah",
    address: "Central Area, Madinah",
    halal: true,
  },
  {
    id: "r13",
    name: "Bateel Cafe",
    distance: "400m from Haram",
    cuisine: "☕ Cafe",
    priceRange: "$$",
    rating: 4.7,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800",
    description: "Dates, pastries, and premium coffee in an elegant cafe.",
    features: ["Halal certified", "Specialty coffee", "Desserts", "Gift dates"],
    lat: 21.4188,
    lng: 39.8255,
    website: "https://www.bateel.com",
    address: "Abraj / Haram shopping area, Makkah",
    halal: true,
  },
  {
    id: "r14",
    name: "Dates & Sweets",
    distance: "200m from Nabawi",
    cuisine: "🍰 Desserts",
    priceRange: "$",
    rating: 4.6,
    isOpen: true,
    type: "ours",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800",
    description: "Perfect stop for sweets, dates, and light refreshments near Nabawi.",
    features: ["Halal certified", "Local sweets", "Gift packs"],
    lat: 24.4678,
    lng: 39.6115,
    website: "https://www.google.com/maps/search/?api=1&query=Dates+sweets+Madinah+Nabawi",
    address: "Near Masjid al-Nabawi, Madinah",
    halal: true,
  },
  {
    id: "r15",
    name: "Al Maqha Cafe",
    distance: "300m from Haram",
    cuisine: "☕ Arabic Coffee",
    priceRange: "$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800",
    description: "Traditional Arabic coffee and snacks with cozy seating.",
    features: ["Halal certified", "Arabic coffee", "Quiet seating"],
    lat: 21.4205,
    lng: 39.8250,
    website: "https://www.google.com/maps/search/?api=1&query=Arabic+coffee+cafe+Makkah",
    address: "Near Haram, Makkah",
    halal: true,
  },

  // ═══════════════════════════════════════════
  // SAUDI / REGIONAL CHAINS
  // ═══════════════════════════════════════════
  {
    id: "kudu-makkah",
    name: "Kudu",
    distance: "6 min walk from Haram",
    cuisine: "🍔 Burgers",
    priceRange: "$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1460306855393-0410f61241c7?w=800",
    description: "Popular Saudi burger chain with breakfast, burgers, and family combos near the Haram area.",
    features: ["Halal certified", "Burgers", "Breakfast", "Family combos"],
    lat: 21.4170,
    lng: 39.8275,
    website: "https://www.kudu.com.sa",
    address: "Ajyad / Ibrahim Al Khalil area, Makkah",
    halal: true,
    chain: "Kudu",
  },
  {
    id: "kudu-madinah",
    name: "Kudu",
    distance: "8 min walk from Nabawi",
    cuisine: "🍔 Burgers",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800",
    description: "Saudi favourite for burgers and breakfast near Masjid al-Nabawi.",
    features: ["Halal certified", "Burgers", "Combos", "Late hours"],
    lat: 24.4655,
    lng: 39.6120,
    website: "https://www.kudu.com.sa",
    address: "Central Madinah near King Fahd Road",
    halal: true,
    chain: "Kudu",
  },
  {
    id: "herfy-makkah",
    name: "Herfy",
    distance: "10 min from Haram",
    cuisine: "🍔 Fast Food",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1586816001966-79b736744398?w=800",
    description: "Long-standing Saudi fast-food brand — burgers, chicken, and value meals for pilgrims.",
    features: ["Halal certified", "Value meals", "Family packing"],
    lat: 21.4155,
    lng: 39.8290,
    website: "https://www.herfy.com",
    address: "Makkah central districts near Haram approaches",
    halal: true,
    chain: "Herfy",
  },
  {
    id: "herfy-madinah",
    name: "Herfy",
    distance: "10 min from Nabawi",
    cuisine: "🍔 Fast Food",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1592861956120-e524fc739696?w=800",
    description: "Reliable Saudi burgers and chicken meals near the Prophet’s Mosque area.",
    features: ["Halal certified", "Burgers", "Chicken", "Takeaway"],
    lat: 24.4640,
    lng: 39.6135,
    website: "https://www.herfy.com",
    address: "Madinah central zone",
    halal: true,
    chain: "Herfy",
  },
  {
    id: "altazaj-makkah",
    name: "Al Tazaj",
    distance: "8 min from Haram",
    cuisine: "🍗 Grilled Chicken",
    priceRange: "$",
    rating: 4.5,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800",
    description: "Famous for fresh charcoal-grilled chicken — a Saudi classic pilgrims love.",
    features: ["Halal certified", "Fresh grill", "Family meals", "Quick service"],
    lat: 21.4160,
    lng: 39.8245,
    website: "https://www.altazaj.com.sa",
    address: "Near Haram / Aziziyah approaches, Makkah",
    halal: true,
    chain: "Al Tazaj",
  },
  {
    id: "altazaj-madinah",
    name: "Al Tazaj",
    distance: "12 min from Nabawi",
    cuisine: "🍗 Grilled Chicken",
    priceRange: "$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800",
    description: "Charcoal-grilled chicken meals popular with families in Madinah.",
    features: ["Halal certified", "Grilled chicken", "Family packs"],
    lat: 24.4625,
    lng: 39.6085,
    website: "https://www.altazaj.com.sa",
    address: "Madinah",
    halal: true,
    chain: "Al Tazaj",
  },
  {
    id: "romansiah-makkah",
    name: "Al Romansiah",
    distance: "800m from Haram",
    cuisine: "🍖 Arabic / Grills",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    description: "Popular Saudi rice & grills chain — large portions ideal for families and groups.",
    features: ["Halal certified", "Family friendly", "Rice meals", "Large portions"],
    lat: 21.4140,
    lng: 39.8300,
    website: "https://www.alromansiah.com",
    address: "Makkah",
    halal: true,
    chain: "Al Romansiah",
  },
  {
    id: "romansiah-madinah",
    name: "Al Romansiah",
    distance: "15 min from Nabawi",
    cuisine: "🍖 Arabic / Grills",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800",
    description: "Saudi rice and grilled meats — great for group pilgrim meals.",
    features: ["Halal certified", "Group seating", "Rice & grills"],
    lat: 24.4600,
    lng: 39.6150,
    website: "https://www.alromansiah.com",
    address: "Madinah",
    halal: true,
    chain: "Al Romansiah",
  },
  {
    id: "nandos-makkah",
    name: "Nando's",
    distance: "Abraj / shopping area",
    cuisine: "🍗 Peri-Peri",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    description: "Flame-grilled peri-peri chicken — popular casual dining in Saudi Arabia.",
    features: ["Halal certified", "Peri-peri chicken", "Dine-in", "Takeaway"],
    lat: 21.4182,
    lng: 39.8250,
    website: "https://www.nandos.sa",
    address: "Makkah retail / Abraj area",
    halal: true,
    chain: "Nando's",
  },
  {
    id: "nandos-madinah",
    name: "Nando's",
    distance: "Near central Madinah malls",
    cuisine: "🍗 Peri-Peri",
    priceRange: "$$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800",
    description: "Peri-peri chicken favourite for families visiting Madinah.",
    features: ["Halal certified", "Flame-grilled", "Family meals"],
    lat: 24.4630,
    lng: 39.6105,
    website: "https://www.nandos.sa",
    address: "Madinah",
    halal: true,
    chain: "Nando's",
  },
  {
    id: "raised-makkah",
    name: "Raised",
    distance: "Near Haram shopping belt",
    cuisine: "🍔 Burgers",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1460306855393-0410f61241c7?w=800",
    description: "Trendy Saudi smash-burger brand loved by younger pilgrims and families.",
    features: ["Halal certified", "Smash burgers", "Modern vibe"],
    lat: 21.4178,
    lng: 39.8268,
    website: "https://www.raised.sa",
    address: "Makkah",
    halal: true,
    chain: "Raised",
  },
  {
    id: "raised-madinah",
    name: "Raised",
    distance: "Central Madinah",
    cuisine: "🍔 Burgers",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800",
    description: "Popular Saudi burger chain with smash-style burgers and shakes.",
    features: ["Halal certified", "Burgers", "Shakes"],
    lat: 24.4658,
    lng: 39.6090,
    website: "https://www.raised.sa",
    address: "Madinah",
    halal: true,
    chain: "Raised",
  },

  // ═══════════════════════════════════════════
  // INTERNATIONAL CHAINS · Makkah
  // ═══════════════════════════════════════════
  {
    id: "mcd-makkah",
    name: "McDonald's",
    distance: "Abraj Al-Bait / Haram area",
    cuisine: "🍔 Fast Food",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1586816001966-79b736744398?w=800",
    description:
      "Multiple McDonald’s branches around Makkah including Haram / Abraj shopping areas — a pilgrim staple for quick meals.",
    features: ["Halal certified", "Multiple branches", "Family meals", "24h some locations"],
    lat: 21.4185,
    lng: 39.8258,
    website: "https://www.mcdonalds.sa",
    address: "Abraj Al-Bait / Haram shopping complex, Makkah",
    halal: true,
    chain: "McDonald's",
  },
  {
    id: "kfc-makkah",
    name: "KFC",
    distance: "Near Haram / Ajyad",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800",
    description: "Kentucky Fried Chicken branches near the Holy Mosque approaches.",
    features: ["Halal certified", "Fried chicken", "Buckets for groups"],
    lat: 21.4190,
    lng: 39.8265,
    website: "https://www.kfc.sa",
    address: "Ajyad / Haram area, Makkah",
    halal: true,
    chain: "KFC",
  },
  {
    id: "bk-makkah",
    name: "Burger King",
    distance: "Haram shopping area",
    cuisine: "🍔 Burgers",
    priceRange: "$",
    rating: 4.1,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1460306855393-0410f61241c7?w=800",
    description: "Flame-grilled burgers near Masjid al-Haram shopping corridors.",
    features: ["Halal certified", "Whopper", "Takeaway"],
    lat: 21.4180,
    lng: 39.8272,
    website: "https://www.burgerking.sa",
    address: "Near Abraj / Ajyad, Makkah",
    halal: true,
    chain: "Burger King",
  },
  {
    id: "pizzahut-makkah",
    name: "Pizza Hut",
    distance: "800m from Haram",
    cuisine: "🍕 Pizza",
    priceRange: "$",
    rating: 4.1,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1579751626657-72bc17010498?w=800",
    description: "Familiar pizza options for families and groups near the Haram.",
    features: ["Halal certified", "Family meals", "Delivery"],
    lat: 21.4165,
    lng: 39.8288,
    website: "https://www.pizzahut.sa",
    address: "Makkah Haram district",
    halal: true,
    chain: "Pizza Hut",
  },
  {
    id: "dominos-makkah",
    name: "Domino's Pizza",
    distance: "Near Haram / Aziziyah taxi",
    cuisine: "🍕 Pizza",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800",
    description: "Quick pizza delivery and takeaway popular with pilgrim groups.",
    features: ["Halal certified", "Delivery", "Group orders"],
    lat: 21.4150,
    lng: 39.8310,
    website: "https://www.dominos.sa",
    address: "Makkah",
    halal: true,
    chain: "Domino's",
  },
  {
    id: "subway-makkah",
    name: "Subway",
    distance: "Abraj Al-Bait mall",
    cuisine: "🥪 Sandwiches",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
    description: "Fresh sandwiches and salads inside Abraj shopping — lighter option near the Haram.",
    features: ["Halal certified", "Custom sandwiches", "Salads"],
    lat: 21.4183,
    lng: 39.8256,
    website: "https://www.subway.com",
    address: "Abraj Al-Bait, Makkah",
    halal: true,
    chain: "Subway",
  },
  {
    id: "popeyes-makkah",
    name: "Popeyes",
    distance: "Near Haram malls",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800",
    description: "Louisiana-style fried chicken — a popular alternative to Al Baik lines.",
    features: ["Halal certified", "Fried chicken", "Sandwiches"],
    lat: 21.4172,
    lng: 39.8260,
    website: "https://www.popeyes.com",
    address: "Makkah retail near Haram",
    halal: true,
    chain: "Popeyes",
  },
  {
    id: "shakeshack-makkah",
    name: "Shake Shack",
    distance: "Abraj Al-Bait mall",
    cuisine: "🍔 Burgers",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    description: "Premium burgers and shakes in the Abraj Al-Bait shopping complex beside the Clock Tower.",
    features: ["Halal certified", "Abraj mall", "Burgers & shakes"],
    lat: 21.4181,
    lng: 39.8254,
    website: "https://www.shakeshack.com",
    address: "Abraj Al-Bait Mall, Makkah",
    halal: true,
    chain: "Shake Shack",
  },
  {
    id: "starbucks-makkah",
    name: "Starbucks",
    distance: "Abraj Al-Bait · 2nd Floor",
    cuisine: "☕ Cafe",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800",
    description:
      "Starbucks Abraj Al Bait (2nd floor) — convenient coffee stop steps from Masjid al-Haram.",
    features: ["Halal certified", "24h most days", "WiFi", "Pastries"],
    lat: 21.4184,
    lng: 39.8257,
    website: "https://locations.starbucks.sa/directory/mecca/abraj-al-bait-2nd-floor",
    address: "Abraj Al Bait - 2nd Floor, Makkah",
    halal: true,
    chain: "Starbucks",
  },
  {
    id: "timhortons-makkah",
    name: "Tim Hortons",
    distance: "Near Haram / Abraj area",
    cuisine: "☕ Cafe",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Makkah",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
    description: "Canadian coffee & donuts chain popular for quick breakfasts before Fajr crowds.",
    features: ["Halal certified", "Coffee", "Donuts", "Breakfast"],
    lat: 21.4176,
    lng: 39.8262,
    website: "https://www.timhortons.sa",
    address: "Makkah Haram / Abraj district",
    halal: true,
    chain: "Tim Hortons",
  },

  // ═══════════════════════════════════════════
  // INTERNATIONAL CHAINS · Madinah
  // ═══════════════════════════════════════════
  {
    id: "mcd-madinah",
    name: "McDonald's",
    distance: "Near Nabawi / King Fahd area",
    cuisine: "🍔 Fast Food",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1586816001966-79b736744398?w=800",
    description: "McDonald’s branches around central Madinah — easy meals after visiting Masjid al-Nabawi.",
    features: ["Halal certified", "Family meals", "Multiple branches"],
    lat: 24.4668,
    lng: 39.6118,
    website: "https://www.mcdonalds.sa",
    address: "Central Madinah near Prophet’s Mosque approaches",
    halal: true,
    chain: "McDonald's",
  },
  {
    id: "kfc-madinah",
    name: "KFC",
    distance: "Near Nabawi central zone",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800",
    description: "KFC near the central Madinah zone for quick fried chicken meals.",
    features: ["Halal certified", "Chicken buckets", "Takeaway"],
    lat: 24.4675,
    lng: 39.6130,
    website: "https://www.kfc.sa",
    address: "Central Madinah",
    halal: true,
    chain: "KFC",
  },
  {
    id: "bk-madinah",
    name: "Burger King",
    distance: "Central Madinah",
    cuisine: "🍔 Burgers",
    priceRange: "$",
    rating: 4.1,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800",
    description: "Burger King for familiar flame-grilled meals near Nabawi.",
    features: ["Halal certified", "Burgers", "Combos"],
    lat: 24.4650,
    lng: 39.6122,
    website: "https://www.burgerking.sa",
    address: "Madinah",
    halal: true,
    chain: "Burger King",
  },
  {
    id: "pizzahut-madinah",
    name: "Pizza Hut",
    distance: "Near Nabawi",
    cuisine: "🍕 Pizza",
    priceRange: "$",
    rating: 4.1,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1579751626657-72bc17010498?w=800",
    description: "Pizza Hut for group dinners after prayers in Madinah.",
    features: ["Halal certified", "Family pizzas", "Delivery"],
    lat: 24.4648,
    lng: 39.6145,
    website: "https://www.pizzahut.sa",
    address: "Madinah central",
    halal: true,
    chain: "Pizza Hut",
  },
  {
    id: "dominos-madinah",
    name: "Domino's Pizza",
    distance: "Central Madinah",
    cuisine: "🍕 Pizza",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    description: "Domino’s delivery and takeaway near Masjid al-Nabawi hotels.",
    features: ["Halal certified", "Delivery", "Late hours"],
    lat: 24.4635,
    lng: 39.6110,
    website: "https://www.dominos.sa",
    address: "Madinah",
    halal: true,
    chain: "Domino's",
  },
  {
    id: "subway-madinah",
    name: "Subway",
    distance: "Near Nabawi hotels",
    cuisine: "🥪 Sandwiches",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
    description: "Fresh sandwiches — lighter option near the Prophet’s Mosque hotels.",
    features: ["Halal certified", "Custom sandwiches", "Healthy options"],
    lat: 24.4670,
    lng: 39.6100,
    website: "https://www.subway.com",
    address: "Central Madinah",
    halal: true,
    chain: "Subway",
  },
  {
    id: "popeyes-madinah",
    name: "Popeyes",
    distance: "Central Madinah",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800",
    description: "Popeyes fried chicken for pilgrims looking for spicy Cajun-style meals.",
    features: ["Halal certified", "Spicy chicken", "Sandwiches"],
    lat: 24.4660,
    lng: 39.6088,
    website: "https://www.popeyes.com",
    address: "Madinah",
    halal: true,
    chain: "Popeyes",
  },
  {
    id: "starbucks-madinah",
    name: "Starbucks",
    distance: "Near Nabawi / malls",
    cuisine: "☕ Cafe",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800",
    description: "Starbucks locations in central Madinah for coffee between prayer times.",
    features: ["Halal certified", "Coffee", "WiFi", "Pastries"],
    lat: 24.4672,
    lng: 39.6098,
    website: "https://locations.starbucks.sa",
    address: "Central Madinah",
    halal: true,
    chain: "Starbucks",
  },
  {
    id: "timhortons-madinah",
    name: "Tim Hortons",
    distance: "Near Nabawi area",
    cuisine: "☕ Cafe",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Madinah",
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800",
    description: "Tim Hortons coffee and baked goods near Madinah’s central pilgrim zone.",
    features: ["Halal certified", "Coffee", "Donuts", "Breakfast"],
    lat: 24.4682,
    lng: 39.6108,
    website: "https://www.timhortons.sa",
    address: "Madinah",
    halal: true,
    chain: "Tim Hortons",
  },
]

export function getRestaurantById(id: string | undefined): Restaurant | undefined {
  if (!id) return undefined
  // Legacy id aliases from older lists
  if (id === "r1" || id === "r16") return RESTAURANTS.find(r => r.id === "albaik-makkah")
  if (id === "r8") return RESTAURANTS.find(r => r.id === "romansiah-makkah")
  if (id === "r17") return RESTAURANTS.find(r => r.id === "kudu-madinah")
  if (id === "r18") return RESTAURANTS.find(r => r.id === "pizzahut-makkah")
  return RESTAURANTS.find(r => r.id === id)
}

export function openRestaurantDirections(restaurant: Restaurant) {
  const lat = Number(restaurant.lat)
  const lng = Number(restaurant.lng)
  if (Number.isFinite(lat) && Number.isFinite(lng)) {
    return `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}&travelmode=walking`
  }
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(
    `${restaurant.name}, ${restaurant.city}, Saudi Arabia`
  )}`
}

function byIds(ids: string[]): Restaurant[] {
  return ids
    .map(id => getRestaurantById(id) ?? RESTAURANTS.find(r => r.id === id))
    .filter((r): r is Restaurant => !!r)
}

/** Hero / recommended — Al Baik always first */
export const recommendedRestaurants = byIds([
  "albaik-makkah",
  "albaik-madinah",
  "r2",
  "mcd-makkah",
  "starbucks-makkah",
  "kudu-makkah",
  "shakeshack-makkah",
])

export const saudiChains = RESTAURANTS.filter(r =>
  ["Al Baik", "Kudu", "Herfy", "Al Tazaj", "Al Romansiah", "Nando's", "Raised"].includes(r.chain ?? "")
)

export const internationalChains = RESTAURANTS.filter(r =>
  [
    "McDonald's",
    "KFC",
    "Burger King",
    "Pizza Hut",
    "Domino's",
    "Subway",
    "Popeyes",
    "Shake Shack",
    "Starbucks",
    "Tim Hortons",
  ].includes(r.chain ?? "")
)

export const nearHaramRestaurants = RESTAURANTS.filter(
  r => r.city === "Makkah" && (r.distance.toLowerCase().includes("haram") || r.distance.toLowerCase().includes("abraj"))
)

export const nearNabawiRestaurants = RESTAURANTS.filter(
  r => r.city === "Madinah" && r.distance.toLowerCase().includes("nabawi")
)

export const cafesAndDesserts = RESTAURANTS.filter(r =>
  r.cuisine.toLowerCase().includes("cafe") ||
  r.cuisine.toLowerCase().includes("coffee") ||
  r.cuisine.toLowerCase().includes("dessert") ||
  r.cuisine.toLowerCase().includes("donut")
)

export const arabicGrills = RESTAURANTS.filter(
  r =>
    !r.chain &&
    (r.cuisine.toLowerCase().includes("arabic") ||
      r.cuisine.toLowerCase().includes("grill") ||
      r.cuisine.toLowerCase().includes("kabab") ||
      r.cuisine.toLowerCase().includes("syrian"))
)
