import { CHAIN_LOGOS, FOOD_PHOTOS, IMAGE_PLACEHOLDER } from "./restaurantImages"

export type RestaurantCity = "Makkah" | "Madinah"
export type RestaurantImageType = "logo" | "photo"

export type Restaurant = {
  id: string
  name: string
  distance: string
  cuisine: string
  priceRange: "$" | "$$" | "$$$"
  rating: number
  isOpen: boolean
  type: "ours" | "external"
  city: RestaurantCity
  /** Primary image (logo URL or photo) */
  image: string
  /** Used when primary fails to load */
  imageFallback: string
  imageType: RestaurantImageType
  description: string
  features: string[]
  lat: number
  lng: number
  website: string
  address: string
  halal: true
  featured?: boolean
  chain?: string
}

function logo(
  logoUrl: string,
  fallbackPhoto: string
): Pick<Restaurant, "image" | "imageFallback" | "imageType"> {
  return { image: logoUrl, imageFallback: fallbackPhoto, imageType: "logo" }
}

function photo(
  url: string,
  fallback = IMAGE_PLACEHOLDER
): Pick<Restaurant, "image" | "imageFallback" | "imageType"> {
  return { image: url, imageFallback: fallback, imageType: "photo" }
}

export const RESTAURANTS: Restaurant[] = [
  // ── Featured hero ──────────────────────────────────────────
  {
    id: "albaik-makkah",
    name: "Al Baik",
    distance: "300m from Haram · Jabal Omar",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.9,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.friedChicken, FOOD_PHOTOS.grilledChicken),
    description:
      "Saudi Arabia’s most iconic broasted chicken chain — a must for pilgrims. Branches near Masjid al-Haram including Jabal Omar.",
    features: ["Halal certified", "Broasted chicken", "Family meals", "Takeaway"],
    lat: 21.4198,
    lng: 39.8232,
    website: "https://www.albaik.com",
    address: "Souk Al Khalil / Jabal Omar, Makkah",
    halal: true,
    featured: true,
    chain: "Al Baik",
  },
  {
    id: "albaik-madinah",
    name: "Al Baik",
    distance: "5 min walk from Nabawi",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.8,
    isOpen: true,
    type: "ours",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.friedChicken, FOOD_PHOTOS.buffet),
    description:
      "Famous Al Baik near Masjid al-Nabawi on King Faisal Road — pilgrims’ favourite after prayers.",
    features: ["Halal certified", "Closest Nabawi branch", "Broasted chicken"],
    lat: 24.4688,
    lng: 39.6102,
    website: "https://www.albaik.com",
    address: "King Faisal Road, Bani Khidrah, Madinah",
    halal: true,
    featured: true,
    chain: "Al Baik",
  },

  // ── Makkah · International chains (logos) ──────────────────
  {
    id: "mcd-makkah",
    name: "McDonald's",
    distance: "Abraj Al-Bait / Haram area",
    cuisine: "🍔 Fast Food",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.mcdonalds, FOOD_PHOTOS.burger),
    description: "Multiple McDonald’s branches around Makkah including Haram / Abraj shopping areas.",
    features: ["Halal certified", "Multiple branches", "Family meals"],
    lat: 21.4185,
    lng: 39.8258,
    website: "https://www.mcdonalds.sa",
    address: "Abraj Al-Bait / Haram complex, Makkah",
    halal: true,
    chain: "McDonald's",
  },
  {
    id: "kfc-makkah",
    name: "KFC",
    distance: "Near Haram / Ajyad",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.kfc, FOOD_PHOTOS.friedChicken),
    description: "Kentucky Fried Chicken near the Holy Mosque approaches.",
    features: ["Halal certified", "Fried chicken", "Buckets for groups"],
    lat: 21.4190,
    lng: 39.8265,
    website: "https://www.kfc.sa",
    address: "Ajyad / Haram area, Makkah",
    halal: true,
    chain: "KFC",
  },
  {
    id: "bk-makkah",
    name: "Burger King",
    distance: "Haram shopping area",
    cuisine: "🍔 Burgers",
    priceRange: "$",
    rating: 4.1,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.burgerKing, FOOD_PHOTOS.burger),
    description: "Flame-grilled burgers near Masjid al-Haram shopping corridors.",
    features: ["Halal certified", "Whopper", "Takeaway"],
    lat: 21.4180,
    lng: 39.8272,
    website: "https://www.burgerking.sa",
    address: "Near Abraj / Ajyad, Makkah",
    halal: true,
    chain: "Burger King",
  },
  {
    id: "pizzahut-makkah",
    name: "Pizza Hut",
    distance: "800m from Haram",
    cuisine: "🍕 Pizza",
    priceRange: "$",
    rating: 4.1,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.pizzaHut, FOOD_PHOTOS.buffet),
    description: "Familiar pizza options for families and groups near the Haram.",
    features: ["Halal certified", "Family meals", "Delivery"],
    lat: 21.4165,
    lng: 39.8288,
    website: "https://www.pizzahut.sa",
    address: "Makkah Haram district",
    halal: true,
    chain: "Pizza Hut",
  },
  {
    id: "dominos-makkah",
    name: "Domino's Pizza",
    distance: "Near Haram / Aziziyah",
    cuisine: "🍕 Pizza",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.dominos, FOOD_PHOTOS.restaurantInterior),
    description: "Quick pizza delivery and takeaway popular with pilgrim groups.",
    features: ["Halal certified", "Delivery", "Group orders"],
    lat: 21.4150,
    lng: 39.8310,
    website: "https://www.dominos.sa",
    address: "Makkah",
    halal: true,
    chain: "Domino's",
  },
  {
    id: "subway-makkah",
    name: "Subway",
    distance: "Abraj Al-Bait mall",
    cuisine: "🥪 Sandwiches",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.subway, FOOD_PHOTOS.restaurantInterior),
    description: "Fresh sandwiches and salads inside Abraj shopping near the Haram.",
    features: ["Halal certified", "Custom sandwiches", "Salads"],
    lat: 21.4183,
    lng: 39.8256,
    website: "https://www.subway.com",
    address: "Abraj Al-Bait, Makkah",
    halal: true,
    chain: "Subway",
  },
  {
    id: "popeyes-makkah",
    name: "Popeyes",
    distance: "Near Haram malls",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.popeyes, FOOD_PHOTOS.friedChicken),
    description: "Louisiana-style fried chicken — a popular alternative near the Haram.",
    features: ["Halal certified", "Fried chicken", "Sandwiches"],
    lat: 21.4172,
    lng: 39.8260,
    website: "https://www.popeyes.com",
    address: "Makkah retail near Haram",
    halal: true,
    chain: "Popeyes",
  },
  {
    id: "shakeshack-makkah",
    name: "Shake Shack",
    distance: "Abraj Al-Bait mall",
    cuisine: "🍔 Burgers",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.shakeShack, FOOD_PHOTOS.burger),
    description: "Premium burgers and shakes in the Abraj Al-Bait shopping complex.",
    features: ["Halal certified", "Abraj mall", "Burgers & shakes"],
    lat: 21.4181,
    lng: 39.8254,
    website: "https://www.shakeshack.com",
    address: "Abraj Al-Bait Mall, Makkah",
    halal: true,
    chain: "Shake Shack",
  },
  {
    id: "starbucks-makkah",
    name: "Starbucks",
    distance: "Abraj Al-Bait · 2nd Floor",
    cuisine: "☕ Cafe",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.starbucks, FOOD_PHOTOS.coffee),
    description: "Starbucks Abraj Al Bait (2nd floor) — steps from Masjid al-Haram.",
    features: ["Halal certified", "24h most days", "WiFi"],
    lat: 21.4184,
    lng: 39.8257,
    website: "https://locations.starbucks.sa/directory/mecca/abraj-al-bait-2nd-floor",
    address: "Abraj Al Bait - 2nd Floor, Makkah",
    halal: true,
    chain: "Starbucks",
  },
  {
    id: "timhortons-makkah",
    name: "Tim Hortons",
    distance: "Near Haram / Abraj area",
    cuisine: "☕ Cafe",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.timHortons, FOOD_PHOTOS.coffee),
    description: "Coffee & donuts — popular for quick breakfasts before prayer crowds.",
    features: ["Halal certified", "Coffee", "Donuts", "Breakfast"],
    lat: 21.4176,
    lng: 39.8262,
    website: "https://www.timhortons.sa",
    address: "Makkah Haram / Abraj district",
    halal: true,
    chain: "Tim Hortons",
  },
  {
    id: "hardees-makkah",
    name: "Hardee's",
    distance: "Near Haram shopping belt",
    cuisine: "🍔 Burgers",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.hardees, FOOD_PHOTOS.burger),
    description: "Hardee’s burgers and breakfast near the Haram area — familiar for international pilgrims.",
    features: ["Halal certified", "Burgers", "Breakfast"],
    lat: 21.4170,
    lng: 39.8270,
    website: "https://www.hardees.com",
    address: "Makkah Haram district",
    halal: true,
    chain: "Hardee's",
  },
  {
    id: "kudu-makkah",
    name: "Kudu",
    distance: "6 min walk from Haram",
    cuisine: "🍔 Burgers",
    priceRange: "$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.kudu, FOOD_PHOTOS.burger),
    description: "Popular Saudi burger chain with breakfast and family combos near the Haram.",
    features: ["Halal certified", "Burgers", "Breakfast", "Family combos"],
    lat: 21.4170,
    lng: 39.8275,
    website: "https://www.kudu.com.sa",
    address: "Ajyad / Ibrahim Al Khalil area, Makkah",
    halal: true,
    chain: "Kudu",
  },
  {
    id: "herfy-makkah",
    name: "Herfy",
    distance: "10 min from Haram",
    cuisine: "🍔 Fast Food",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.burger, FOOD_PHOTOS.friedChicken),
    description: "Long-standing Saudi fast-food brand — burgers, chicken, and value meals.",
    features: ["Halal certified", "Value meals", "Family packing"],
    lat: 21.4155,
    lng: 39.8290,
    website: "https://www.herfy.com",
    address: "Makkah central districts",
    halal: true,
    chain: "Herfy",
  },

  // ── Makkah · Saudi / Arabic / hotel dining ─────────────────
  {
    id: "altazaj-makkah",
    name: "Al Tazaj",
    distance: "8 min from Haram",
    cuisine: "🍗 Grilled Chicken",
    priceRange: "$",
    rating: 4.5,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.grilledChicken, FOOD_PHOTOS.arabicGrill),
    description: "Famous for fresh charcoal-grilled chicken — a Saudi classic pilgrims love.",
    features: ["Halal certified", "Fresh grill", "Family meals"],
    lat: 21.4160,
    lng: 39.8245,
    website: "https://www.altazaj.com.sa",
    address: "Near Haram approaches, Makkah",
    halal: true,
    chain: "Al Tazaj",
  },
  {
    id: "romansiah-makkah",
    name: "Al Romansiah",
    distance: "800m from Haram",
    cuisine: "🍖 Arabic / Grills",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.arabicGrill, FOOD_PHOTOS.kabsaRice),
    description: "Popular Saudi rice & grills chain — large portions for families and groups.",
    features: ["Halal certified", "Family friendly", "Rice meals"],
    lat: 21.4140,
    lng: 39.8300,
    website: "https://www.alromansiah.com",
    address: "Makkah",
    halal: true,
    chain: "Al Romansiah",
  },
  {
    id: "nandos-makkah",
    name: "Nando's",
    distance: "Abraj / shopping area",
    cuisine: "🍗 Peri-Peri",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...logo(CHAIN_LOGOS.nandos, FOOD_PHOTOS.grilledChicken),
    description: "Flame-grilled peri-peri chicken — popular casual dining in Saudi Arabia.",
    features: ["Halal certified", "Peri-peri chicken", "Dine-in"],
    lat: 21.4182,
    lng: 39.8250,
    website: "https://www.nandos.sa",
    address: "Makkah retail / Abraj area",
    halal: true,
    chain: "Nando's",
  },
  {
    id: "r2",
    name: "Zamzam Restaurant",
    distance: "Abraj Al-Bait",
    cuisine: "🍖 Arabic",
    priceRange: "$$",
    rating: 4.7,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.restaurantInterior, FOOD_PHOTOS.arabicGrill),
    description: "Traditional Arabic dishes in the Abraj Al-Bait area near Masjid al-Haram.",
    features: ["Halal certified", "Arabic platters", "Family sections"],
    lat: 21.4185,
    lng: 39.8255,
    website: "https://www.google.com/maps/search/?api=1&query=Zamzam+Restaurant+Abraj+Al+Bait",
    address: "Abraj Al-Bait, Makkah",
    halal: true,
  },
  {
    id: "r5",
    name: "Al Nakheel Restaurant",
    distance: "200m from Haram",
    cuisine: "🍖 Arabic",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.kabsaRice, FOOD_PHOTOS.arabicGrill),
    description: "Simple Arabic comfort food at affordable prices near the Haram.",
    features: ["Halal certified", "Budget friendly", "Casual dining"],
    lat: 21.4210,
    lng: 39.8265,
    website: "https://www.google.com/maps/search/?api=1&query=Al+Nakheel+Restaurant+Makkah",
    address: "Near Haram, Makkah",
    halal: true,
  },
  {
    id: "kabsa-aseel-makkah",
    name: "Matam Al Kabsa Al Aseel",
    distance: "Near Haram",
    cuisine: "🍖 Kabsa",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.kabsaRice, FOOD_PHOTOS.arabicGrill),
    description: "Authentic Saudi kabsa and rice dishes — a pilgrim favourite for hearty meals.",
    features: ["Halal certified", "Kabsa", "Family portions"],
    lat: 21.4200,
    lng: 39.8275,
    website: "https://www.google.com/maps/search/?api=1&query=Matam+Al+Kabsa+Al+Aseel+Makkah",
    address: "Makkah Haram area",
    halal: true,
  },
  {
    id: "layali-makkah",
    name: "Layali Al Sham",
    distance: "Near Haram",
    cuisine: "🌍 Syrian",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.shawarma, FOOD_PHOTOS.arabicGrill),
    description: "Levantine grills and mezze popular with Syrian and Arab pilgrims in Makkah.",
    features: ["Halal certified", "Grills", "Mixed platters"],
    lat: 21.4195,
    lng: 39.8280,
    website: "https://www.google.com/maps/search/?api=1&query=Layali+Al+Sham+Makkah",
    address: "Makkah",
    halal: true,
  },
  {
    id: "raised-makkah",
    name: "Raised",
    distance: "Near Haram shopping belt",
    cuisine: "🍔 Burgers",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.burger, FOOD_PHOTOS.restaurantInterior),
    description: "Trendy Saudi smash-burger brand loved by younger pilgrims.",
    features: ["Halal certified", "Smash burgers", "Modern vibe"],
    lat: 21.4178,
    lng: 39.8268,
    website: "https://www.raised.sa",
    address: "Makkah",
    halal: true,
    chain: "Raised",
  },
  {
    id: "fairmont-gold-lounge",
    name: "Fairmont Gold Lounge Restaurant",
    distance: "Clock Tower · Abraj Al-Bait",
    cuisine: "✨ Fine Dining",
    priceRange: "$$$",
    rating: 4.7,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.fineDining, FOOD_PHOTOS.lounge),
    description: "Exclusive Fairmont Gold dining lounge inside the Clock Royal Tower with refined service.",
    features: ["Halal certified", "Hotel dining", "Lounge access"],
    lat: 21.4189,
    lng: 39.8252,
    website: "https://www.fairmont.com/en/hotels/makkah/makkah-clock-royal-tower.html",
    address: "Fairmont Makkah Clock Royal Tower, Abraj Al-Bait",
    halal: true,
  },
  {
    id: "clove-swissotel",
    name: "Clove Restaurant Swissôtel",
    distance: "Abraj Al-Bait · Swissôtel",
    cuisine: "✨ Fine Dining",
    priceRange: "$$$",
    rating: 4.6,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.lounge, FOOD_PHOTOS.fineDining),
    description: "Clove restaurant at Swissôtel Makkah — international and Arabic buffet dining near the Haram.",
    features: ["Halal certified", "Buffet", "Hotel restaurant"],
    lat: 21.4185,
    lng: 39.8258,
    website: "https://www.swissotel.com/hotels/makkah/",
    address: "Swissôtel Makkah, Abraj Al-Bait",
    halal: true,
  },

  // ── Madinah · Chains ───────────────────────────────────────
  {
    id: "kfc-madinah",
    name: "KFC",
    distance: "Near Nabawi central zone",
    cuisine: "🍗 Fast Food",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...logo(CHAIN_LOGOS.kfc, FOOD_PHOTOS.friedChicken),
    description: "KFC near the central Madinah zone for quick fried chicken meals.",
    features: ["Halal certified", "Chicken buckets", "Takeaway"],
    lat: 24.4675,
    lng: 39.6130,
    website: "https://www.kfc.sa",
    address: "Central Madinah",
    halal: true,
    chain: "KFC",
  },
  {
    id: "mcd-madinah",
    name: "McDonald's",
    distance: "Near Nabawi / King Fahd area",
    cuisine: "🍔 Fast Food",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...logo(CHAIN_LOGOS.mcdonalds, FOOD_PHOTOS.burger),
    description: "McDonald’s around central Madinah — easy meals after visiting Masjid al-Nabawi.",
    features: ["Halal certified", "Family meals", "Multiple branches"],
    lat: 24.4668,
    lng: 39.6118,
    website: "https://www.mcdonalds.sa",
    address: "Central Madinah",
    halal: true,
    chain: "McDonald's",
  },
  {
    id: "bk-madinah",
    name: "Burger King",
    distance: "Central Madinah",
    cuisine: "🍔 Burgers",
    priceRange: "$",
    rating: 4.1,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...logo(CHAIN_LOGOS.burgerKing, FOOD_PHOTOS.burger),
    description: "Burger King for familiar flame-grilled meals near Nabawi.",
    features: ["Halal certified", "Burgers", "Combos"],
    lat: 24.4650,
    lng: 39.6122,
    website: "https://www.burgerking.sa",
    address: "Madinah",
    halal: true,
    chain: "Burger King",
  },
  {
    id: "kudu-madinah",
    name: "Kudu",
    distance: "8 min walk from Nabawi",
    cuisine: "🍔 Burgers",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...logo(CHAIN_LOGOS.kudu, FOOD_PHOTOS.burger),
    description: "Saudi favourite for burgers and breakfast near Masjid al-Nabawi.",
    features: ["Halal certified", "Burgers", "Combos"],
    lat: 24.4655,
    lng: 39.6120,
    website: "https://www.kudu.com.sa",
    address: "Central Madinah near King Fahd Road",
    halal: true,
    chain: "Kudu",
  },
  {
    id: "herfy-madinah",
    name: "Herfy",
    distance: "10 min from Nabawi",
    cuisine: "🍔 Fast Food",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.burger, FOOD_PHOTOS.friedChicken),
    description: "Reliable Saudi burgers and chicken meals near the Prophet’s Mosque area.",
    features: ["Halal certified", "Burgers", "Chicken"],
    lat: 24.4640,
    lng: 39.6135,
    website: "https://www.herfy.com",
    address: "Madinah central zone",
    halal: true,
    chain: "Herfy",
  },
  {
    id: "pizzahut-madinah",
    name: "Pizza Hut",
    distance: "Near Nabawi",
    cuisine: "🍕 Pizza",
    priceRange: "$",
    rating: 4.1,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...logo(CHAIN_LOGOS.pizzaHut, FOOD_PHOTOS.buffet),
    description: "Pizza Hut for group dinners after prayers in Madinah.",
    features: ["Halal certified", "Family pizzas", "Delivery"],
    lat: 24.4648,
    lng: 39.6145,
    website: "https://www.pizzahut.sa",
    address: "Madinah central",
    halal: true,
    chain: "Pizza Hut",
  },
  {
    id: "subway-madinah",
    name: "Subway",
    distance: "Near Nabawi hotels",
    cuisine: "🥪 Sandwiches",
    priceRange: "$",
    rating: 4.2,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...logo(CHAIN_LOGOS.subway, FOOD_PHOTOS.restaurantInterior),
    description: "Fresh sandwiches — lighter option near the Prophet’s Mosque hotels.",
    features: ["Halal certified", "Custom sandwiches"],
    lat: 24.4670,
    lng: 39.6100,
    website: "https://www.subway.com",
    address: "Central Madinah",
    halal: true,
    chain: "Subway",
  },
  {
    id: "starbucks-madinah",
    name: "Starbucks",
    distance: "Near Nabawi / malls",
    cuisine: "☕ Cafe",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...logo(CHAIN_LOGOS.starbucks, FOOD_PHOTOS.coffee),
    description: "Starbucks in central Madinah for coffee between prayer times.",
    features: ["Halal certified", "Coffee", "WiFi"],
    lat: 24.4672,
    lng: 39.6098,
    website: "https://locations.starbucks.sa",
    address: "Central Madinah",
    halal: true,
    chain: "Starbucks",
  },

  // ── Madinah · Arabic / local / hotel ───────────────────────
  {
    id: "romansiah-madinah",
    name: "Al Romansiah",
    distance: "15 min from Nabawi",
    cuisine: "🍖 Arabic / Grills",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.arabicGrill, FOOD_PHOTOS.kabsaRice),
    description: "Saudi rice and grilled meats — great for group pilgrim meals.",
    features: ["Halal certified", "Group seating", "Rice & grills"],
    lat: 24.4600,
    lng: 39.6150,
    website: "https://www.alromansiah.com",
    address: "Madinah",
    halal: true,
    chain: "Al Romansiah",
  },
  {
    id: "altazaj-madinah",
    name: "Al Tazaj",
    distance: "12 min from Nabawi",
    cuisine: "🍗 Grilled Chicken",
    priceRange: "$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.grilledChicken, FOOD_PHOTOS.arabicGrill),
    description: "Charcoal-grilled chicken meals popular with families in Madinah.",
    features: ["Halal certified", "Grilled chicken", "Family packs"],
    lat: 24.4625,
    lng: 39.6085,
    website: "https://www.altazaj.com.sa",
    address: "Madinah",
    halal: true,
    chain: "Al Tazaj",
  },
  {
    id: "r3",
    name: "Layali Al Sham",
    distance: "500m from Nabawi",
    cuisine: "🌍 Syrian",
    priceRange: "$$",
    rating: 4.6,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.shawarma, FOOD_PHOTOS.arabicGrill),
    description: "Authentic Levantine meals with grilled specialties near Masjid al-Nabawi.",
    features: ["Halal certified", "Grills", "Mixed platters"],
    lat: 24.4695,
    lng: 39.6135,
    website: "https://www.google.com/maps/search/?api=1&query=Layali+Al+Sham+Madinah",
    address: "Central Area, Madinah",
    halal: true,
  },
  {
    id: "alandalus-madinah",
    name: "Al Andalus Restaurant",
    distance: "Near Nabawi",
    cuisine: "🍖 Arabic",
    priceRange: "$$",
    rating: 4.4,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.arabicGrill, FOOD_PHOTOS.restaurantInterior),
    description: "Arabic and Andalusian-inspired dishes in central Madinah near the Prophet’s Mosque.",
    features: ["Halal certified", "Arabic cuisine", "Family seating"],
    lat: 24.4680,
    lng: 39.6115,
    website: "https://www.google.com/maps/search/?api=1&query=Al+Andalus+Restaurant+Madinah",
    address: "Central Madinah",
    halal: true,
  },
  {
    id: "nakheel-madinah",
    name: "Matam Nakheel Madinah",
    distance: "Near Nabawi",
    cuisine: "🍖 Arabic",
    priceRange: "$",
    rating: 4.3,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.kabsaRice, FOOD_PHOTOS.buffet),
    description: "Local Arabic restaurant serving rice, grills, and everyday pilgrim meals.",
    features: ["Halal certified", "Budget friendly", "Local flavours"],
    lat: 24.4675,
    lng: 39.6125,
    website: "https://www.google.com/maps/search/?api=1&query=Matam+Nakheel+Madinah",
    address: "Madinah",
    halal: true,
  },
  {
    id: "oberoi-restaurant-madinah",
    name: "Oberoi Restaurant Madinah",
    distance: "Facing Nabawi · Oberoi",
    cuisine: "✨ Fine Dining",
    priceRange: "$$$",
    rating: 4.8,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.fineDining, FOOD_PHOTOS.lounge),
    description: "Fine dining at The Oberoi, Madina — elegant hotel restaurant overlooking Masjid al-Nabawi.",
    features: ["Halal certified", "Hotel dining", "Luxury"],
    lat: 24.4690,
    lng: 39.6085,
    website: "https://www.oberoihotels.com/hotels-in-madina/",
    address: "The Oberoi, Madina, Abizar Road",
    halal: true,
  },
  {
    id: "anwar-lounge-madinah",
    name: "Anwar Lounge Mövenpick",
    distance: "2 min from Nabawi",
    cuisine: "☕ Lounge",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "external",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.lounge, FOOD_PHOTOS.coffee),
    description: "Lounge dining at Anwar Al Madinah Mövenpick — light meals and coffee near Nabawi.",
    features: ["Halal certified", "Hotel lounge", "Light meals"],
    lat: 24.4678,
    lng: 39.6105,
    website: "https://movenpick.accor.com/en/middle-east/saudi-arabia/madinah/hotel-madinah-anwar.html",
    address: "Anwar Al Madinah Mövenpick, Central Zone",
    halal: true,
  },

  // ── Kept popular locals ────────────────────────────────────
  {
    id: "r4",
    name: "Makkah Grill House",
    distance: "100m from Haram",
    cuisine: "🍖 Grills",
    priceRange: "$$",
    rating: 4.5,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.buffet, FOOD_PHOTOS.arabicGrill),
    description: "Charcoal-grilled meats and fresh sides very close to Haram.",
    features: ["Halal certified", "BBQ", "Quick service"],
    lat: 21.4220,
    lng: 39.8258,
    website: "https://www.google.com/maps/search/?api=1&query=Makkah+Grill+House",
    address: "Ajyad area, Makkah",
    halal: true,
  },
  {
    id: "r6",
    name: "Haram View Cafe",
    distance: "80m from Haram",
    cuisine: "☕ Cafe",
    priceRange: "$",
    rating: 4.6,
    isOpen: true,
    type: "ours",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.coffee, FOOD_PHOTOS.restaurantInterior),
    description: "Light meals and coffee with a convenient Haram-side location.",
    features: ["Halal certified", "Coffee", "Snacks"],
    lat: 21.4222,
    lng: 39.8260,
    website: "https://www.google.com/maps/search/?api=1&query=Cafe+near+Masjid+al+Haram",
    address: "Haram perimeter, Makkah",
    halal: true,
  },
  {
    id: "r13",
    name: "Bateel Cafe",
    distance: "400m from Haram",
    cuisine: "☕ Cafe",
    priceRange: "$$",
    rating: 4.7,
    isOpen: true,
    type: "external",
    city: "Makkah",
    ...photo(FOOD_PHOTOS.desserts, FOOD_PHOTOS.coffee),
    description: "Dates, pastries, and premium coffee in an elegant cafe.",
    features: ["Halal certified", "Specialty coffee", "Gift dates"],
    lat: 21.4188,
    lng: 39.8255,
    website: "https://www.bateel.com",
    address: "Abraj / Haram shopping area, Makkah",
    halal: true,
  },
  {
    id: "r14",
    name: "Dates & Sweets",
    distance: "200m from Nabawi",
    cuisine: "🍰 Desserts",
    priceRange: "$",
    rating: 4.6,
    isOpen: true,
    type: "ours",
    city: "Madinah",
    ...photo(FOOD_PHOTOS.desserts, FOOD_PHOTOS.kabsaRice),
    description: "Perfect stop for sweets, dates, and light refreshments near Nabawi.",
    features: ["Halal certified", "Local sweets", "Gift packs"],
    lat: 24.4678,
    lng: 39.6115,
    website: "https://www.google.com/maps/search/?api=1&query=Dates+sweets+Madinah",
    address: "Near Masjid al-Nabawi, Madinah",
    halal: true,
  },
]

export function getRestaurantById(id: string | undefined): Restaurant | undefined {
  if (!id) return undefined
  if (id === "r1" || id === "r16") return RESTAURANTS.find(r => r.id === "albaik-makkah")
  if (id === "r8") return RESTAURANTS.find(r => r.id === "romansiah-makkah")
  if (id === "r17") return RESTAURANTS.find(r => r.id === "kudu-madinah")
  if (id === "r18") return RESTAURANTS.find(r => r.id === "pizzahut-makkah")
  return RESTAURANTS.find(r => r.id === id)
}

export function openRestaurantDirections(restaurant: Restaurant) {
  const lat = Number(restaurant.lat)
  const lng = Number(restaurant.lng)
  if (Number.isFinite(lat) && Number.isFinite(lng)) {
    return `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}&travelmode=walking`
  }
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(
    `${restaurant.name}, ${restaurant.city}, Saudi Arabia`
  )}`
}

function byIds(ids: string[]): Restaurant[] {
  return ids
    .map(id => getRestaurantById(id) ?? RESTAURANTS.find(r => r.id === id))
    .filter((r): r is Restaurant => !!r)
}

/** Curated sections — each venue leads in one primary row to avoid repetition */
export const recommendedRestaurants = byIds([
  "albaik-makkah",
  "altazaj-madinah",
  "shakeshack-makkah",
  "r2", // Zamzam Restaurant
  "romansiah-madinah",
  "fairmont-gold-lounge",
  "r14", // Dates & Sweets
  "raised-makkah",
])

export const nearHaramRestaurants = byIds([
  "albaik-makkah",
  "shakeshack-makkah",
  "subway-makkah",
  "r6", // Haram View Cafe
  "r13", // Bateel
  "clove-swissotel",
  "nandos-makkah",
  "herfy-makkah",
])

export const nearNabawiRestaurants = byIds([
  "albaik-madinah",
  "mcd-madinah",
  "kudu-madinah",
  "pizzahut-madinah",
  "starbucks-madinah",
  "anwar-lounge-madinah",
  "oberoi-restaurant-madinah",
  "herfy-madinah",
])

export const saudiChains = byIds([
  "kudu-makkah",
  "altazaj-makkah",
  "romansiah-makkah",
  "raised-makkah",
  "herfy-madinah",
  "altazaj-madinah",
  "romansiah-madinah",
  "kudu-madinah",
])

export const internationalChains = byIds([
  "mcd-makkah",
  "kfc-makkah",
  "bk-makkah",
  "pizzahut-makkah",
  "dominos-makkah",
  "popeyes-makkah",
  "hardees-makkah",
  "kfc-madinah",
  "bk-madinah",
  "subway-madinah",
])

export const arabicGrills = byIds([
  "r2", // Zamzam
  "r5", // Al Nakheel Makkah
  "kabsa-aseel-makkah",
  "layali-makkah",
  "r4", // Grill House
  "alandalus-madinah",
  "nakheel-madinah",
  "r3", // Layali Madinah
])

export const cafesAndDesserts = byIds([
  "starbucks-makkah",
  "timhortons-makkah",
  "fairmont-gold-lounge",
  "r14", // Dates & Sweets
  "anwar-lounge-madinah",
])

export { IMAGE_PLACEHOLDER }
