/** Real Nigerian travel agents directory (Excel-sourced). */

export type TravelAgentCountry = {
  id: string
  name: string
  flag: string
  comingSoon?: boolean
}

export type TravelAgent = {
  id: string
  countryId: string
  agencyName: string
  city: string
  address: string
  phone: string | null
  phone2?: string | null
  email: string | null
  services: string[]
  featured: boolean
}

export const TRAVEL_AGENT_CONTACT_EMAIL = "ahmadado6002@gmail.com"

export const DEFAULT_AGENT_SERVICES = [
  "Umrah Packages",
  "Hajj Services",
  "Flight Booking",
  "Hotel Booking",
] as const

export const TRAVEL_AGENT_COUNTRIES: TravelAgentCountry[] = [
  { id: "nigeria", name: "Nigeria", flag: "🇳🇬" },
  { id: "egypt", name: "Egypt", flag: "🇪🇬", comingSoon: true },
  { id: "uk", name: "United Kingdom", flag: "🇬🇧", comingSoon: true },
  { id: "pakistan", name: "Pakistan", flag: "🇵🇰", comingSoon: true },
  { id: "bangladesh", name: "Bangladesh", flag: "🇧🇩", comingSoon: true },
  { id: "indonesia", name: "Indonesia", flag: "🇮🇩", comingSoon: true },
  { id: "france", name: "France", flag: "🇫🇷", comingSoon: true },
  { id: "algeria", name: "Algeria", flag: "🇩🇿", comingSoon: true },
  { id: "morocco", name: "Morocco", flag: "🇲🇦", comingSoon: true },
  { id: "turkey", name: "Turkey", flag: "🇹🇷", comingSoon: true },
]

export const TRAVEL_AGENTS: TravelAgent[] = [
  {
    id: "ng-1-le-meridian-air-services-ltd",
    countryId: "nigeria",
    agencyName: "LE-MERIDIAN AIR SERVICES LTD",
    city: "Kano",
    address: "9A Post Office Road, Kano",
    phone: null,
    email: null,
    services: [...DEFAULT_AGENT_SERVICES],
    featured: false,
  },
  {
    id: "ng-2-luday-travel-services-ltd",
    countryId: "nigeria",
    agencyName: "LUDAY TRAVEL SERVICES LTD",
    city: "Kano",
    address: "Suit B16, No 14/15 Ummi Plaza Trade Fair Complex, Kano",
    phone: "08033333668",
    phone2: "08034448557",
    email: "luday_travel@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-3-m-m-yahaya-sons-ltd",
    countryId: "nigeria",
    agencyName: "M&M YAHAYA & SONS LTD",
    city: "Kano",
    address: "No. Sharada Phase 1, Kano",
    phone: "08065078878",
    email: "mmyandsonsltd@gmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-4-m-t-a-travels-and-tours-limited",
    countryId: "nigeria",
    agencyName: "M.T.A TRAVELS AND TOURS LIMITED",
    city: "Kano",
    address: "No 5 Magwan Audu Bako Way, Kano",
    phone: "08033114025",
    phone2: "08022903222",
    email: "magwantatt@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-5-mabrook-travel-and-tours-ltd",
    countryId: "nigeria",
    agencyName: "MABROOK TRAVEL AND TOURS LTD",
    city: "Kano",
    address: "No 5, Civic Center Road, Kano",
    phone: "08035865872",
    email: "mabrooktravel@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-6-masanawa-travel-agent-ltd",
    countryId: "nigeria",
    agencyName: "MASANAWA TRAVEL AGENT LTD",
    city: "Kano",
    address: "No 13 Zaria Road Opp. Kano State House",
    phone: "08032477880",
    email: "masanawatravel@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-7-masha-allah-travel-agent-ltd",
    countryId: "nigeria",
    agencyName: "MASHA ALLAH TRAVEL AGENT LTD",
    city: "Kano",
    address: "No. 4 Zoo Road, Kano",
    phone: "08152720001",
    phone2: "08033497397",
    email: "mashaallahtravelagency@gmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-8-mecca-medina-travel-agent-ltd",
    countryId: "nigeria",
    agencyName: "MECCA MEDINA TRAVEL AGENT LTD",
    city: "Kano",
    address: "5 Ibrahim Taiwo Road, Kano",
    phone: "08033960941",
    phone2: "08065645779",
    email: "mmtal58@hotmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-9-meeqat-travel-agent-ltd",
    countryId: "nigeria",
    agencyName: "MEEQAT TRAVEL AGENT LTD",
    city: "Kano",
    address: "No. 9, Ibrahim Taiwo Road, Kano",
    phone: "08023048180",
    phone2: "08023106975",
    email: "meeqattravels@gmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-10-memlad-tours-ltd",
    countryId: "nigeria",
    agencyName: "MEMLAD TOURS LTD",
    city: "Kaduna",
    address: "12 Emir Rd, Ang. Rimi Lowcoast, Kaduna",
    phone: "08034528160",
    email: null,
    services: [...DEFAULT_AGENT_SERVICES],
    featured: false,
  },
  {
    id: "ng-11-mfak-travel-and-tours-limited",
    countryId: "nigeria",
    agencyName: "MFAK TRAVEL AND TOURS LIMITED",
    city: "Kano",
    address: "No 63 Ibrahim Taiwo, Kano",
    phone: "08023091591",
    email: "mafaktravels@hotmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-12-msl-travel-tours-nigeria-limited",
    countryId: "nigeria",
    agencyName: "MSL TRAVEL & TOURS NIGERIA LIMITED",
    city: "Kano",
    address: "No. 59 Ibrahim Taiwo Road, Kano",
    phone: "08023724155",
    phone2: "08023726814",
    email: "msltravels@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-13-mubash-shirin-air-services-ltd",
    countryId: "nigeria",
    agencyName: "MUBASH SHIRIN AIR SERVICES LTD",
    city: "Kano",
    address: "No. 36C Beirut Road, Kano",
    phone: "08033494023",
    email: "mubashair55@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-14-mu-min-travels-and-tours-ltd",
    countryId: "nigeria",
    agencyName: "MU'MIN TRAVELS AND TOURS LTD",
    city: "Kano",
    address: "No. 1, IBB Way, Kano",
    phone: "08035865400",
    email: "mumintravels2014@gmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-15-mungadi-taiseer-travel-tours-ltd",
    countryId: "nigeria",
    agencyName: "MUNGADI & TAISEER TRAVEL & TOURS LTD",
    city: "Kano",
    address: "No. 12/13 Gidan Buhari Road, Kano",
    phone: "08065846965",
    phone2: "08098846965",
    email: "mungad_altaiseer@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-16-murna-travel-agent",
    countryId: "nigeria",
    agencyName: "MURNA TRAVEL AGENT",
    city: "Kano",
    address: "Gidan Badamasi, No. 25 Niger Street, Kano",
    phone: "08035955359",
    email: "murnatravelagency@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-17-namira-umrah-hajj-services-ltd",
    countryId: "nigeria",
    agencyName: "NAMIRA UMRAH & HAJJ SERVICES LTD",
    city: "Kano",
    address: "No. 63 El-Duniya Complex, Ibrahim Taiwo Road, Kano",
    phone: "08036379380",
    phone2: "07031225400",
    email: "namira.ltd@gmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-18-nasaf-travel-tours-ltd",
    countryId: "nigeria",
    agencyName: "NASAF TRAVEL & TOURS LTD",
    city: "Kano",
    address: "No. 5 Hospital Road, Kano",
    phone: "08069776880",
    phone2: "08056201622",
    email: "nasaftravelskano@gmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-19-new-era-travel-and-tours-ltd",
    countryId: "nigeria",
    agencyName: "NEW ERA TRAVEL AND TOURS LTD",
    city: "Kano",
    address: "No 3 Beirut Road, Kano",
    phone: "08033325593",
    email: "neweralag@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-20-nusra-travel-agent-ltd",
    countryId: "nigeria",
    agencyName: "NUSRA TRAVEL AGENT LTD",
    city: "Kano",
    address: "No. 34 Beirut Road, Kano",
    phone: "08033468442",
    email: null,
    services: [...DEFAULT_AGENT_SERVICES],
    featured: false,
  },
  {
    id: "ng-21-oasis-air-service-limited",
    countryId: "nigeria",
    agencyName: "OASIS AIR SERVICE LIMITED",
    city: "Kano",
    address: "61 Ibrahim Taiwo Road, Kano",
    phone: null,
    email: "oasistravel37@hotmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: false,
  },
  {
    id: "ng-22-rahama-air-service-limited",
    countryId: "nigeria",
    agencyName: "RAHAMA AIR SERVICE LIMITED",
    city: "Kano",
    address: "20 Civil Centre Road, Kano",
    phone: "08027747352",
    email: "rahamair@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-23-royal-first-class-travel-tours",
    countryId: "nigeria",
    agencyName: "ROYAL FIRST CLASS TRAVEL & TOURS",
    city: "Kano",
    address: "No 5 Civic Center Road, Kano",
    phone: "08033340620",
    phone2: "07028306040",
    email: "muhammadgogel@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-24-sahihul-arafat-air-service",
    countryId: "nigeria",
    agencyName: "SAHIHUL ARAFAT AIR SERVICE",
    city: "Kano",
    address: "No. 170 Murtala Muhammad Way, Kano",
    phone: "08035450465",
    phone2: "07039030029",
    email: "sahihularafat@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-25-sanilak-travel-tours-limited",
    countryId: "nigeria",
    agencyName: "SANILAK TRAVEL & TOURS LIMITED",
    city: "Kano",
    address: "60 Zoo Road, Kano",
    phone: "08033149028",
    phone2: "08054837783",
    email: "slkmatatravels@gmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-26-shami-travel-agent",
    countryId: "nigeria",
    agencyName: "SHAMI TRAVEL AGENT",
    city: "Kano",
    address: "71 Ibrahim Taiwo Road, Kano",
    phone: "08023855123",
    email: "shamitravels@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-27-silhovette-travel-agent-ltd",
    countryId: "nigeria",
    agencyName: "SILHOVETTE TRAVEL AGENT LTD",
    city: "Kano",
    address: "No 78 Ibrahim Taiwo Road, Kano",
    phone: "08051563699",
    phone2: "08037766572",
    email: "shilhovettetravels@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-28-sky-trust-travel-agent-ltd",
    countryId: "nigeria",
    agencyName: "SKY TRUST TRAVEL AGENT LTD",
    city: "Kano",
    address: "48 Unity Road, Kano",
    phone: "08023041543",
    email: "skytrusttravels@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-29-skygate-travels-and-tours-limited",
    countryId: "nigeria",
    agencyName: "SKYGATE TRAVELS AND TOURS LIMITED",
    city: "Kano",
    address: "13B Post Office Road, Kano",
    phone: "08037034690",
    phone2: "08053466312",
    email: "skygatetravel@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-30-soli-air-service-ltd",
    countryId: "nigeria",
    agencyName: "SOLI AIR SERVICE LTD",
    city: "Kano",
    address: "32 Beirut Road, Kano",
    phone: "064892511",
    email: "soliatirltd@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-31-soltan-travels-and-tours-limited",
    countryId: "nigeria",
    agencyName: "SOLTAN TRAVELS AND TOURS LIMITED",
    city: "Kano",
    address: "Gidan Sani Kwangila, Zoo Road, Kano",
    phone: null,
    email: null,
    services: [...DEFAULT_AGENT_SERVICES],
    featured: false,
  },
  {
    id: "ng-32-super-wings-air-services-ltd",
    countryId: "nigeria",
    agencyName: "SUPER WINGS AIR SERVICES LTD",
    city: "Kano",
    address: "9 Beirut Road, Kano",
    phone: null,
    email: "superairservice@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: false,
  },
  {
    id: "ng-33-talas-air-services",
    countryId: "nigeria",
    agencyName: "TALAS AIR SERVICES",
    city: "Kano",
    address: "No. 34 Beirut Road, Kano",
    phone: "08037129099",
    email: "talasair@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-34-the-traveller-enterprises-ltd",
    countryId: "nigeria",
    agencyName: "THE TRAVELLER ENTERPRISES LTD",
    city: "Kano",
    address: "No. 71 Ibrahim Taiwo Road, Kano",
    phone: "08037861651",
    phone2: "08054002063",
    email: "abdulaziznaibi@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-35-t-i-c-travel-and-tours-limited",
    countryId: "nigeria",
    agencyName: "T.I.C TRAVEL AND TOURS LIMITED",
    city: "Kano",
    address: "No 3 Beirut Road, Kano",
    phone: null,
    email: "tictravelstours@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: false,
  },
  {
    id: "ng-36-tofa-travel-agent-ltd",
    countryId: "nigeria",
    agencyName: "TOFA TRAVEL AGENT LTD",
    city: "Kano",
    address: "No. 492 U.D.B. Road, Kano",
    phone: "08036892128",
    email: "tofa2travel@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-37-tura-travels-and-tours-ltd",
    countryId: "nigeria",
    agencyName: "TURA TRAVELS AND TOURS LTD",
    city: "Kano",
    address: "No. 2 Beirut Road, Kano",
    phone: null,
    email: null,
    services: [...DEFAULT_AGENT_SERVICES],
    featured: false,
  },
  {
    id: "ng-38-u-a-travels-and-tours-limited",
    countryId: "nigeria",
    agencyName: "U.A. TRAVELS AND TOURS LIMITED",
    city: "Kano",
    address: "255 Tarauni Along Juma'at Mosque, Kano",
    phone: "08066982277",
    email: "ua.travels@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-39-universal-isma-umra-travel-agent-ltd",
    countryId: "nigeria",
    agencyName: "UNIVERSAL ISMA UMRA TRAVEL AGENT LTD",
    city: "Kano",
    address: "No 1 Bompai Road Opp Central Hotel, Kano",
    phone: "08023095763",
    email: "ismoumarah@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-40-yakasai-air-travels-limited",
    countryId: "nigeria",
    agencyName: "YAKASAI AIR TRAVELS LIMITED",
    city: "Kano",
    address: "No. 10 Zoo Road, Sky House, Kano",
    phone: "08033477541",
    phone2: "08033958187",
    email: "yksair@post.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-41-yammata-tours-limited",
    countryId: "nigeria",
    agencyName: "YAMMATA TOURS LIMITED",
    city: "Kano",
    address: "34 Beirut Road, Kano",
    phone: "08033140286",
    phone2: "08044122588",
    email: null,
    services: [...DEFAULT_AGENT_SERVICES],
    featured: false,
  },
  {
    id: "ng-42-yusra-travels-and-tours-limited",
    countryId: "nigeria",
    agencyName: "YUSRA TRAVELS AND TOURS LIMITED",
    city: "Kano",
    address: "9 Buhari Triangle, Zoo Road, Kano",
    phone: "08065846965",
    email: "yusuratravelsandtours@gmail.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-43-zago-global-links-nigeria-ltd",
    countryId: "nigeria",
    agencyName: "ZAGO GLOBAL LINKS NIGERIA LTD",
    city: "Kano",
    address: "59 Murtala Mohd Way, Kano",
    phone: "08037035051",
    email: "danzago114@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-44-zango-travel-and-tours-ltd",
    countryId: "nigeria",
    agencyName: "ZANGO TRAVEL AND TOURS LTD",
    city: "Kano",
    address: "No. 54 Ibrahim Taiwo Road, Kano",
    phone: "064641557",
    email: "zangotravel@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-45-zeenest-travel-tours-ltd",
    countryId: "nigeria",
    agencyName: "ZEENEST TRAVEL & TOURS LTD",
    city: "Kano",
    address: "No. 65 Ardiyya House Behind Radio Kano",
    phone: "07055904051",
    email: "zeenestravel@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
  {
    id: "ng-46-zirga-zirga-travel-agent",
    countryId: "nigeria",
    agencyName: "ZIRGA-ZIRGA TRAVEL AGENT",
    city: "Kano",
    address: "14 Katsina Road, Kano",
    phone: "08023585558",
    email: "abelcom4@yahoo.com",
    services: [...DEFAULT_AGENT_SERVICES],
    featured: true,
  },
]

/** Convert local NG numbers (0803…) to WhatsApp digits (234803…). */
export function toWhatsAppNumber(phone: string | null | undefined): string | null {
  if (!phone) return null
  const digits = phone.replace(/\D/g, "")
  if (!digits) return null
  if (digits.startsWith("234")) return digits
  if (digits.startsWith("0")) return `234${digits.slice(1)}`
  if (digits.length === 10) return `234${digits}`
  return digits
}

export function toTelHref(phone: string | null | undefined): string | null {
  const wa = toWhatsAppNumber(phone)
  return wa ? `tel:+${wa}` : null
}

export function getTravelAgentCountry(id: string | string[] | undefined) {
  const key = Array.isArray(id) ? id[0] : id
  if (!key) return null
  return TRAVEL_AGENT_COUNTRIES.find(c => c.id === key) ?? null
}

export function getAgentsForCountry(countryId: string) {
  return TRAVEL_AGENTS.filter(a => a.countryId === countryId)
    .slice()
    .sort((a, b) => Number(b.featured) - Number(a.featured) || a.agencyName.localeCompare(b.agencyName))
}

export function getTravelAgentById(id: string | string[] | undefined) {
  const key = Array.isArray(id) ? id[0] : id
  if (!key) return null
  return TRAVEL_AGENTS.find(a => a.id === key) ?? null
}

export function getAgentCountForCountry(countryId: string) {
  return TRAVEL_AGENTS.filter(a => a.countryId === countryId).length
}

